from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = PROJECT_ROOT / "artifacts" / "project-outputs"
SUBMISSION_DIR = PROJECT_ROOT / "artifacts" / "submission-package"
CONFIG_PATH = PROJECT_ROOT / "code" / "config" / "round6_config_template.json"
ROUND6_SCRIPT = PROJECT_ROOT / "code" / "project-scripts" / "round6_numpy_passive_d2nn.py"
ROUND6_METRICS = OUTPUT_DIR / "round6_numpy_passive_d2nn_metrics.csv"
ROUND6_SUMMARY_JSON = OUTPUT_DIR / "round6_numpy_passive_d2nn_summary.json"
ROUND6_SUMMARY_MD = OUTPUT_DIR / "round6_numpy_passive_d2nn_summary.md"
ROUND6_PANEL = OUTPUT_DIR / "round6_numpy_passive_d2nn_panel.png"
ROUND6_HISTORY = OUTPUT_DIR / "round6_numpy_passive_d2nn_training_history.json"
RUN_LOG = PROJECT_ROOT / "logs" / "round6_rerun_20260430T010105Z.md"


def ensure_dirs() -> None:
    SUBMISSION_DIR.mkdir(parents=True, exist_ok=True)


def read_metrics() -> list[dict[str, str]]:
    with ROUND6_METRICS.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def read_summary() -> dict:
    return json.loads(ROUND6_SUMMARY_JSON.read_text(encoding="utf-8"))


def write_csv(rows: list[dict[str, object]], target: Path) -> None:
    with target.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def generate_source_data(metrics_rows: list[dict[str, str]], summary: dict) -> None:
    rows: list[dict[str, object]] = []
    for row in metrics_rows:
        rows.append(
            {
                "table_section": "raw_metrics",
                "split": row["split"],
                "sample": row["sample"],
                "condition": row["condition"],
                "psnr_db": row["psnr_db"],
                "mse": row["mse"],
                "ood_mean_psnr_db": "",
                "ood_mean_mse": "",
                "train_final_mse": "",
                "comparison": "",
                "delta_db": "",
            }
        )

    for row in summary["summary_rows"]:
        rows.append(
            {
                "table_section": "condition_summary",
                "split": "ood",
                "sample": "mean",
                "condition": row["condition"],
                "psnr_db": "",
                "mse": "",
                "ood_mean_psnr_db": f'{row["ood_mean_psnr_db"]:.6f}',
                "ood_mean_mse": f'{row["ood_mean_mse"]:.8f}',
                "train_final_mse": f'{row["train_final_mse"]:.8f}',
                "comparison": "",
                "delta_db": "",
            }
        )

    for name, value in summary["deltas_db"].items():
        rows.append(
            {
                "table_section": "delta_summary",
                "split": "ood",
                "sample": "mean",
                "condition": "common_path",
                "psnr_db": "",
                "mse": "",
                "ood_mean_psnr_db": "",
                "ood_mean_mse": "",
                "train_final_mse": "",
                "comparison": name.replace("common_minus_", ""),
                "delta_db": f"{value:.6f}",
            }
        )

    write_csv(rows, SUBMISSION_DIR / "figure5_source_data.csv")


def generate_data_availability() -> None:
    text = """# Data Availability

Source data underlying Fig. 5 are provided with this study as `figure5_source_data.csv` in `artifacts/submission-package/`. The underlying numerical outputs generated by the restored round6 processor-level baseline are stored in `artifacts/project-outputs/`, including the raw per-sample metrics table, the summary JSON, the summary Markdown file, the panel image and the training-history JSON. Additional project data are available from the corresponding author upon reasonable request.
"""
    (SUBMISSION_DIR / "data_availability.md").write_text(text, encoding="utf-8")


def generate_code_availability() -> None:
    text = """# Code Availability

The code used to generate the restored round6 processor-level baseline is included in this project space under `code/project-scripts/round6_numpy_passive_d2nn.py`. The script that regenerates the manuscript-facing source-data and registry files is provided as `code/project-scripts/refresh_submission_package.py`. Additional project code will continue to be archived in this GitHub-backed long-term project space and can be deposited to a public archival repository before submission if required by the journal.
"""
    (SUBMISSION_DIR / "code_availability.md").write_text(text, encoding="utf-8")


def generate_methods_reproducibility(summary: dict) -> None:
    by_condition = {row["condition"]: row for row in summary["summary_rows"]}
    text = f"""# Methods Reproducibility

## Round6 baseline
The restored round6 processor-level baseline was rerun from `code/project-scripts/round6_numpy_passive_d2nn.py` inside this long-term project space. The script writes all primary outputs to `artifacts/project-outputs/`.

## Verified outputs from this project space
- ordinary OOD mean PSNR: {by_condition["ordinary"]["ood_mean_psnr_db"]:.6f} dB
- common-path OOD mean PSNR: {by_condition["common_path"]["ood_mean_psnr_db"]:.6f} dB
- non-common-path OOD mean PSNR: {by_condition["noncommon_path"]["ood_mean_psnr_db"]:.6f} dB
- wrong-reference OOD mean PSNR: {by_condition["wrong_reference"]["ood_mean_psnr_db"]:.6f} dB
- common minus ordinary: {summary["deltas_db"]["common_minus_ordinary_db"]:.6f} dB
- common minus non-common-path: {summary["deltas_db"]["common_minus_noncommon_db"]:.6f} dB
- common minus wrong-reference: {summary["deltas_db"]["common_minus_wrongref_db"]:.6f} dB

## Reproducibility boundary
This restored round6 baseline is a minimal NumPy-based passive D2NN rebuild. It closes the raw-output chain for Fig. 5 source-data generation, but the summary note in the script explicitly marks it as a reproducible baseline rather than a submission-grade final result.
"""
    (SUBMISSION_DIR / "methods_reproducibility.md").write_text(text, encoding="utf-8")


def generate_registry(summary: dict) -> None:
    rows = [
        {
            "artifact_name": "round6_numpy_passive_d2nn.py",
            "artifact_type": "script",
            "location": str(ROUND6_SCRIPT),
            "status": "available",
            "role": "primary generator for round6 outputs",
            "source": "restored from previous long-term project space and adapted to relative paths",
        },
        {
            "artifact_name": "round6_numpy_passive_d2nn_metrics.csv",
            "artifact_type": "raw_metrics",
            "location": str(ROUND6_METRICS),
            "status": "available",
            "role": "primary raw Fig. 5 metrics table",
            "source": "generated by rerunning round6 script in current long-term project space",
        },
        {
            "artifact_name": "round6_numpy_passive_d2nn_summary.json",
            "artifact_type": "summary_json",
            "location": str(ROUND6_SUMMARY_JSON),
            "status": "available",
            "role": "machine-readable round6 summary",
            "source": "generated by rerunning round6 script in current long-term project space",
        },
        {
            "artifact_name": "figure5_source_data.csv",
            "artifact_type": "source_data",
            "location": str(SUBMISSION_DIR / "figure5_source_data.csv"),
            "status": "generated_from_raw_round6_outputs",
            "role": "Nature Communications Fig. 5 source-data table",
            "source": "assembled from raw metrics and summary JSON in current long-term project space",
        },
        {
            "artifact_name": "round6_rerun_20260430T010105Z.md",
            "artifact_type": "run_log",
            "location": str(RUN_LOG),
            "status": "available",
            "role": "execution log",
            "source": "created during restored round6 rerun",
        },
    ]
    write_csv(rows, SUBMISSION_DIR / "reproducibility_registry.csv")


def md5(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def generate_md5_registry() -> None:
    targets = [
        ROUND6_SCRIPT,
        CONFIG_PATH,
        ROUND6_METRICS,
        ROUND6_SUMMARY_MD,
        ROUND6_SUMMARY_JSON,
        ROUND6_PANEL,
        ROUND6_HISTORY,
        RUN_LOG,
        SUBMISSION_DIR / "figure5_source_data.csv",
        SUBMISSION_DIR / "data_availability.md",
        SUBMISSION_DIR / "code_availability.md",
        SUBMISSION_DIR / "methods_reproducibility.md",
        SUBMISSION_DIR / "reproducibility_registry.csv",
    ]
    rows = [
        {"path": str(path), "file_name": path.name, "md5": md5(path), "size_bytes": path.stat().st_size}
        for path in targets
    ]
    write_csv(rows, SUBMISSION_DIR / "md5_registry.csv")


def main() -> None:
    ensure_dirs()
    metrics_rows = read_metrics()
    summary = read_summary()
    generate_source_data(metrics_rows, summary)
    generate_data_availability()
    generate_code_availability()
    generate_methods_reproducibility(summary)
    generate_registry(summary)
    generate_md5_registry()


if __name__ == "__main__":
    main()
